'use client';

import Link from 'next/link';
import { useUser } from '@clerk/nextjs';
import Image from 'next/image';

export default function HomePage() {
	const { isLoaded, isSignedIn, user } = useUser();

	const ytSampleImages = ['/yt-01.png', '/yt-02.jpg', '/yt-03.jpg', '/yt-04.png'];

	const reelSampleImages = [
		'/reel-01.png',
		'/reel-02.jpg',
		'/reel-03.png',
		'/reel-04.png',
	];

	// Loading state
	if (!isLoaded) {
		return (
			<div className="min-h-screen bg-[#0a0a0a] flex items-center justify-center">
				<div className="text-center">
					<div className="w-12 h-12 border-2 border-orange-500 border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
					<div className="text-gray-300 font-medium">Loading...</div>
				</div>
			</div>
		);
	}

	// Signed out content
	if (!isSignedIn) {
		return (
			<div className="min-h-screen bg-[#0a0a0a] relative overflow-hidden">
				{/* Background effects */}
				<div className="absolute inset-0">
					<div className="absolute top-1/4 left-1/4 w-96 h-96 bg-orange-500/10 rounded-full blur-3xl"></div>
					<div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-orange-400/10 rounded-full blur-3xl"></div>
					<div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-gradient-to-r from-orange-500/5 to-orange-400/5 rounded-full blur-3xl"></div>
				</div>

				<div className="relative z-10 container mx-auto px-4 py-20">
					<div className="text-center max-w-4xl mx-auto">
						<div className="mb-8">
							<h1 className="text-7xl md:text-8xl font-extrabold mb-6 tracking-tight text-white">
								Thumbly
							</h1>
							<div className="w-32 h-1 bg-orange-500 mx-auto rounded-full mb-8"></div>
						</div>

						{/* Bold Taglines */}
						<div className="mb-12">
							<h2 className="text-3xl md:text-5xl font-bold mb-6 text-white leading-tight">
								Get your video thumbnails within{' '}
								<span className="text-orange-500">seconds</span>
							</h2>
							<p className="text-xl md:text-2xl mb-4 text-gray-300 font-medium">
								Whether it&apos;s for{' '}
								<span className="text-red-400">YouTube</span> or{' '}
								<span className="text-purple-400">Reels</span>
							</p>
							<p className="text-lg md:text-xl mb-8 text-gray-400 max-w-3xl mx-auto leading-relaxed">
								Transform your content with AI-powered thumbnails that grab
								attention and boost your click-through rates instantly
							</p>
						</div>

						<div className="flex flex-col sm:flex-row gap-6 justify-center items-center mb-20">
							<Link href="/sign-up">
								<button className="bg-orange-500 hover:bg-orange-600 text-white px-10 py-4 rounded-2xl text-lg font-semibold hover:shadow-2xl hover:shadow-orange-500/25 transition-all duration-300 hover-lift">
									Get Started Free
								</button>
							</Link>
							<Link href="/sign-in">
								<button className="glass-effect text-gray-300 px-10 py-4 rounded-2xl text-lg font-semibold hover:text-white hover:bg-white/10 transition-all duration-300 border border-gray-700 hover:border-gray-600">
									Sign In
								</button>
							</Link>
						</div>

						{/* Example Images Section */}
						<div className="mb-20">
							<h3 className="text-2xl md:text-3xl font-bold mb-4 text-white">
								See What&apos;s Possible
							</h3>
							<p className="text-gray-400 mb-12 text-lg">
								Real thumbnails generated by our AI in seconds
							</p>

							{/* YouTube Examples */}
							<div className="mb-16">
								<div className="flex items-center justify-center gap-3 mb-8">
									<span className="text-2xl">📺</span>
									<h4 className="text-xl font-semibold text-white">
										YouTube Thumbnails
									</h4>
									<span className="bg-red-500 text-white text-xs px-2 py-1 rounded-full">
										16:9
									</span>
								</div>
								<div className="grid grid-cols-1 md:grid-cols-2 gap-8">
									{/* YouTube Example Cards */}
									{ytSampleImages.map((item) => (
										<div
											key={item}
											className="glass-effect rounded-2xl overflow-hidden hover-lift group">
											<div className="aspect-video bg-gray-800 relative flex items-center justify-center">
												<Image
													src={item}
													alt={`YouTube Example ${item}`}
													fill
													className="object-cover"
												/>
											</div>
											<div className="p-4">
												<p className="text-sm text-gray-400">
													Generated in 7.4s
												</p>
											</div>
										</div>
									))}
								</div>
							</div>

							{/* Reels Examples */}
							<div className="mb-16">
								<div className="flex items-center justify-center gap-3 mb-8">
									<span className="text-2xl">📱</span>
									<h4 className="text-xl font-semibold text-white">
										Reels Thumbnails
									</h4>
									<span className="bg-purple-500 text-white text-xs px-2 py-1 rounded-full">
										9:16
									</span>
								</div>
								<div className="flex justify-center">
									<div className="grid grid-cols-2 gap-8 max-w-2xl w-full">
										{/* Reels Example Cards */}
										{reelSampleImages.map((item) => (
											<div
												key={item}
												className="glass-effect rounded-2xl overflow-hidden hover-lift group">
												<div className="aspect-[9/16] bg-gray-800 relative flex items-center justify-center">
													<Image
														src={item}
														alt={`Reel Example ${item}`}
														fill
														className="object-cover"
													/>
												</div>
												<div className="p-4">
													<p className="text-sm text-gray-400">
														Generated in 2.8s
													</p>
												</div>
											</div>
										))}
									</div>
								</div>
							</div>

							{/* Stats */}
							<div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-16">
								<div className="text-center">
									<div className="text-4xl font-bold text-orange-500 mb-2">
										10K+
									</div>
									<div className="text-gray-400">Thumbnails Generated</div>
								</div>
								<div className="text-center">
									<div className="text-4xl font-bold text-orange-500 mb-2">
										2.5s
									</div>
									<div className="text-gray-400">Average Generation Time</div>
								</div>
								<div className="text-center">
									<div className="text-4xl font-bold text-orange-500 mb-2">
										95%
									</div>
									<div className="text-gray-400">User Satisfaction</div>
								</div>
							</div>
						</div>

						{/* Feature preview */}
						<div className="mt-20 grid grid-cols-1 md:grid-cols-3 gap-8 text-left">
							<div className="glass-effect p-6 rounded-2xl hover-lift">
								<div className="w-12 h-12 bg-gradient-to-br from-orange-500 to-orange-600 rounded-xl flex items-center justify-center mb-4">
									<span className="text-2xl">🎨</span>
								</div>
								<h3 className="text-xl font-semibold mb-2 text-white">
									AI-Powered Design
								</h3>
								<p className="text-gray-400">
									Advanced algorithms create unique, eye-catching thumbnails
									tailored to your content
								</p>
							</div>
							<div className="glass-effect p-6 rounded-2xl hover-lift">
								<div className="w-12 h-12 bg-gradient-to-br from-orange-400 to-orange-500 rounded-xl flex items-center justify-center mb-4">
									<span className="text-2xl">⚡</span>
								</div>
								<h3 className="text-xl font-semibold mb-2 text-white">
									Lightning Fast
								</h3>
								<p className="text-gray-400">
									Generate multiple thumbnail variations in seconds, not hours
								</p>
							</div>
							<div className="glass-effect p-6 rounded-2xl hover-lift">
								<div className="w-12 h-12 bg-gradient-to-br from-orange-600 to-orange-700 rounded-xl flex items-center justify-center mb-4">
									<span className="text-2xl">🎯</span>
								</div>
								<h3 className="text-xl font-semibold mb-2 text-white">
									High Conversion
								</h3>
								<p className="text-gray-400">
									Optimized designs proven to increase click-through rates
								</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		);
	}

	// Signed in content
	return (
		<div className="min-h-screen bg-[#0a0a0a] relative overflow-hidden">
			{/* Background effects */}
			<div className="absolute inset-0">
				<div className="absolute top-1/4 left-1/4 w-96 h-96 bg-orange-500/10 rounded-full blur-3xl"></div>
				<div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-orange-400/10 rounded-full blur-3xl"></div>
				<div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-gradient-to-r from-orange-500/5 to-orange-400/5 rounded-full blur-3xl"></div>
			</div>

			<div className="relative z-10 container mx-auto px-4 py-20">
				<div className="text-center max-w-4xl mx-auto">
					<div className="mb-8">
						<h1 className="text-7xl md:text-8xl font-extrabold mb-6 tracking-tight text-white">
							Thumbly
						</h1>
						<div className="w-32 h-1 bg-orange-500 mx-auto rounded-full mb-8"></div>
					</div>

					{/* Greeting Section for Signed-in Users */}
					<div className="mb-12">
						<h2 className="text-4xl md:text-6xl font-bold mb-6 text-white leading-tight">
							Welcome Back
						</h2>
						<p className="text-xl md:text-2xl mb-4 text-gray-300 font-medium">
							Hello,{' '}
							<span className="text-orange-500 font-bold">
								{user?.firstName || 'Creator'}
							</span>
							! 👋
						</p>
						<p className="text-lg md:text-xl mb-8 text-gray-400 max-w-3xl mx-auto leading-relaxed">
							Ready to create amazing thumbnails that will captivate your
							audience? Let&apos;s get started!
						</p>
					</div>

					<div className="flex flex-col sm:flex-row gap-6 justify-center items-center mb-20">
						<Link href="/dashboard">
							<button className="bg-orange-500 hover:bg-orange-600 text-white px-10 py-4 rounded-2xl text-lg font-semibold hover:shadow-2xl hover:shadow-orange-500/25 transition-all duration-300 hover-lift">
								Go to Dashboard
							</button>
						</Link>
						<Link href="/gallery">
							<button className="glass-effect text-gray-300 px-10 py-4 rounded-2xl text-lg font-semibold hover:text-white hover:bg-white/10 transition-all duration-300 border border-gray-700 hover:border-gray-600">
								View Gallery
							</button>
						</Link>
					</div>

					{/* Example Images Section */}
					<div className="mb-20">
						<h3 className="text-2xl md:text-3xl font-bold mb-4 text-white">
							See What&apos;s Possible
						</h3>
						<p className="text-gray-400 mb-12 text-lg">
							Real thumbnails generated by our AI in seconds
						</p>

						{/* YouTube Examples */}
						<div className="mb-16">
							<div className="flex items-center justify-center gap-3 mb-8">
								<span className="text-2xl">📺</span>
								<h4 className="text-xl font-semibold text-white">
									YouTube Thumbnails
								</h4>
								<span className="bg-red-500 text-white text-xs px-2 py-1 rounded-full">
									16:9
								</span>
							</div>
							<div className="grid grid-cols-1 md:grid-cols-2 gap-8">
								{/* YouTube Example Cards */}
								{ytSampleImages.map((item) => (
									<div
										key={item}
										className="glass-effect rounded-2xl overflow-hidden hover-lift group">
										<div className="aspect-video bg-gray-800 relative flex items-center justify-center">
											<Image
												src={item}
												alt={`YouTube Example ${item}`}
												fill
												className="object-cover"
											/>
										</div>
										<div className="p-4">
											<p className="text-sm text-gray-400">
												Generated in 7.4s
											</p>
										</div>
									</div>
								))}
							</div>
						</div>

						{/* Reels Examples */}
						<div className="mb-16">
							<div className="flex items-center justify-center gap-3 mb-8">
								<span className="text-2xl">📱</span>
								<h4 className="text-xl font-semibold text-white">
									Reels Thumbnails
								</h4>
								<span className="bg-purple-500 text-white text-xs px-2 py-1 rounded-full">
									9:16
								</span>
							</div>
							<div className="flex justify-center">
								<div className="grid grid-cols-2 gap-8 max-w-2xl w-full">
									{/* Reels Example Cards */}
									{reelSampleImages.map((item) => (
										<div
											key={item}
											className="glass-effect rounded-2xl overflow-hidden hover-lift group">
											<div className="aspect-[9/16] bg-gray-800 relative flex items-center justify-center">
												<Image
													src={item}
													alt={`Reel Example ${item}`}
													fill
													className="object-cover"
												/>
											</div>
											<div className="p-4">
												<p className="text-sm text-gray-400">
													Generated in 2.8s
												</p>
											</div>
										</div>
									))}
								</div>
							</div>
						</div>

						{/* Stats */}
						<div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-16">
							<div className="text-center">
								<div className="text-4xl font-bold text-orange-500 mb-2">
									10K+
								</div>
								<div className="text-gray-400">Thumbnails Generated</div>
							</div>
							<div className="text-center">
								<div className="text-4xl font-bold text-orange-500 mb-2">
									2.5s
								</div>
								<div className="text-gray-400">Average Generation Time</div>
							</div>
							<div className="text-center">
								<div className="text-4xl font-bold text-orange-500 mb-2">
									95%
								</div>
								<div className="text-gray-400">User Satisfaction</div>
							</div>
						</div>
					</div>

					{/* Feature preview */}
					<div className="mt-20 grid grid-cols-1 md:grid-cols-3 gap-8 text-left">
						<div className="glass-effect p-6 rounded-2xl hover-lift">
							<div className="w-12 h-12 bg-gradient-to-br from-orange-500 to-orange-600 rounded-xl flex items-center justify-center mb-4">
								<span className="text-2xl">🎨</span>
							</div>
							<h3 className="text-xl font-semibold mb-2 text-white">
								AI-Powered Design
							</h3>
							<p className="text-gray-400">
								Advanced algorithms create unique, eye-catching thumbnails
								tailored to your content
							</p>
						</div>
						<div className="glass-effect p-6 rounded-2xl hover-lift">
							<div className="w-12 h-12 bg-gradient-to-br from-orange-400 to-orange-500 rounded-xl flex items-center justify-center mb-4">
								<span className="text-2xl">⚡</span>
							</div>
							<h3 className="text-xl font-semibold mb-2 text-white">
								Lightning Fast
							</h3>
							<p className="text-gray-400">
								Generate multiple thumbnail variations in seconds, not hours
							</p>
						</div>
						<div className="glass-effect p-6 rounded-2xl hover-lift">
							<div className="w-12 h-12 bg-gradient-to-br from-orange-600 to-orange-700 rounded-xl flex items-center justify-center mb-4">
								<span className="text-2xl">🎯</span>
							</div>
							<h3 className="text-xl font-semibold mb-2 text-white">
								High Conversion
							</h3>
							<p className="text-gray-400">
								Optimized designs proven to increase click-through rates
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	);
}
